[package]
name = "nom_graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom_game = { path = "../nom_game" }
rogalik = { path = "../../../rogalik" }
